import "bootstrap/dist/css/bootstrap.min.css";
import Head from "next/head";
import Header from "../Containers/Header";
import PersonalFlex from "../data/personalFlex";
import HomeWrapper from "../Wrappers/HomeWrapper";
import InputGroup from "../data/inputGroup";
import Inputs from "../Components/inputs/inputs";
import Leftside from "../Components/leftSide/leftside";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pointer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <HomeWrapper>
        <Leftside />
        {/* ======== SideBar ========== */}
        <div className="SideBar">
          <h1 className="registration mb-0">Registration</h1>
          <div className="d-flex align-items-center">
            {PersonalFlex.map((value, index) => {
              return (
                <div
                  key={index}
                  className={`personal_flex d-flex align-items-center ${value.className}`}
                >
                  <img
                    className={`circle ${value.circle}`}
                    src={value.img}
                    alt="check"
                  />
                  <p className={`subtitle mb-0 ${value.className}`}>
                    {value.subtitle}
                  </p>
                </div>
              );
            })}
          </div>

          {/* form-inputs */}
          <form className="form d-flex" action="#">
            <div className="d-flex flex-wrap align-items-center ">
              {InputGroup.map((value, index) => {
                return (
                  <Inputs
                    type={value.type}
                    key={index}
                    width={`${value.width}`}
                    img={`${value.img ? value.img : ""}`}
                    placeholder={`${value.placeholder}`}
                    inputClass={`${value.inputClass}`}
                    imgClass={`${value.imgClass}`}
                  />
                );
              })}
              <img className="calendar1" src="calendar.svg" alt="photo" />
              <img className="vactor" src="vactor.svg" alt="photo" />
              <img className="calendar2" src="calendar.svg" alt="photo" />
            </div>

            {/* //=== rightSide ===*/}
            <div className="rightSide">
              <div>
                <img className="user" src="user.svg" alt="bigUser" />
                <button className="upload_btn">
                  <img className="plus" src="plus.svg" alt="plus" />
                  <p className="mb-0 subtitle">Upload image </p>
                </button>
              </div>
              <div className="radio_group">
                <img className="gender" src="gender.svg" alt="gender" />
                <div className="d-flex align-items-center">
                  <div className="d-flex align-items-center">
                    <p className="mb-0 subtitle">Male</p>
                    <img src="active_radio.svg" alt="radio" />
                  </div>
                  <div className="d-flex align-items-center ms-4">
                    <p
                      className="mb-0 subtitle"
                      style={{ marginRight: "10px" }}
                    >
                      Female
                    </p>
                    <img src="radio.svg" alt="radio" />
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </HomeWrapper>
    </div>
  );
}
